book/urls.py
from django.urls import path , re_path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # path('',views.index , name='index'),
    path('',login_required(views.BookListView.as_view(),login_url='/login'), name='index'),
    # path('detail/<slug:slug>/', views.detail, name='detail'),
    path('detail/<slug:slug>/', views.BookDetailView.as_view(), name='detail'),
    re_path(r'add/$', views.book_add, name='book_add'),

    re_path(r'cart/add/(?P<slug>[\w-]+)/$', views.cart_add, name='cart_add'),
    re_path(r'cart/delete/(?P<slug>[\w-]+)/$', views.cart_delete, name='cart_delete'),
    re_path(r'cart/list/$', views.cart_list, name='cart_list'),
    re_path(r'cart/checkout/$', views.cart_checkout, name='cart_checkout'),
]

testproject/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf .urls.static import static
from book.api import router as book_router
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('myapp.urls', 'myapp'), namespace='myapp')),
    path('book/', include(('book.urls', 'book'), namespace='book')),
    path('api/', include(book_router.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models
from django.utils.html import format_html

# Create your models here.

BOOK_LEVEL_CHOICES = (
    ('B', 'Basic'),
    ('M', 'Medium'),
    ('A', 'Advanced'),
)

class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Category' #ชื่อใหม่

    def __str__(self):
        return self.name

class Author(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Author' 

    def __str__(self):
        return self.name

class Book(models.Model):
    category = models.ForeignKey(Category,null=True,blank=True,on_delete=models.CASCADE) # 1 หมวดหมู่ มีหลายหนังสือ
    author = models.ManyToManyField(Author,blank=True)
    code = models.CharField(max_length=10,unique=True)
    slug = models.SlugField(max_length=200,unique=True)
    name = models.CharField(max_length=100)
    description = models.TextField(null=True,blank=True)
    price = models.FloatField(default=0)
    published = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    level = models.CharField(max_length=20,choices=BOOK_LEVEL_CHOICES,null=True,blank=True)
    image = models.FileField(upload_to='upload/',null=True,blank=True)
    class Meta:
        ordering = ['-created']
        verbose_name_plural = 'Book' 

    def show_image(self):
        if self.image: # มีการอัปโหลดภาพไหม
            return format_html('<img src="%s" height="40px" />'% self.image.url)
        return '-'
    show_image.allow_tags = True
    show_image.short_description = 'Image'

    def get_comment_count(self):
        return self.bookcomment_set.count()

    def __str__(self):
        return self.name

class BookComment(models.Model):
    book = models.ForeignKey(Book,on_delete=models.CASCADE) # หนังสือ 1 เล่มมีหลาย comment
    comment = models.CharField(max_length=100)
    rating = models.FloatField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['id']
        verbose_name_plural = 'Book Comment'

    def __str__(self):
        return self.comment

book/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        exclude = ['id', 'slug', 'published', 'created', 'updated']
    
    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        self.fields['code'].error_messages = {'required': 'Please enter code'}
        self.fields['name'].error_messages = {'required': 'Please enter name'}
        self.fields['price'].error_messages = {'required': 'Please enter price','invalid': 'Please enter a valid price'}

    def clean(self):
        cleaned_data = super(BookForm, self).clean()
        if not cleaned_data.get('category'):
            self.add_error('category', 'Please select category')
        
        if not cleaned_data.get('author'):
            self.add_error('author', 'Please select author')

book/views.py
from django.core.mail import EmailMessage
from django.shortcuts import get_object_or_404, render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Category, Book
from .forms import BookForm
from slugify import slugify
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def index(request):
    categories = Category.objects.all() # ดึงข้อมูลหมวดหมู่ทั้งหมด
    books = Book.objects.filter(published=True) # ดึงข้อมูลหนังสือที่เผยแพร่

    categ_id = request.GET.get('categoryid')
    if categ_id:
        #ถ้า categoryid มีค่า
        books = books.filter(category_id=categ_id)
    
    pagination = Paginator(books,10)
    page = request.GET.get('page')
    try:
        books = pagination.page(page)
    except PageNotAnInteger:
        books = pagination.page(1)
    except EmptyPage:
        books = pagination.page(pagination.num_pages)

    return render(request, 'book/index.html',{
        'books': books, 
        'categories': categories,
        'categ_id': categ_id
    })

def detail(request, slug):
    book = get_object_or_404(Book, slug=slug)
    return render(request, 'book/detail.html', {
        'book': book
    })

def book_add(request):
    form = BookForm()
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            book = form.save(commit=False)
            book.slug = slugify(book.name)
            book.published = True
            book.save()
            form.save_m2m()
            messages.success(request, 'Save success')
            return HttpResponseRedirect(reverse('book:index', kwargs={}))
        messages.error(request, 'Save failed!')
    return render(request, 'book/add.html', {
        'form': form
    })

from django.views.generic import ListView , DeleteView
class BookListView(ListView):
    model = Book
    template_name = 'book/index.html'
    context_object_name = 'books'
    paginate_by = 5

    def get_queryset(self):
        return Book.objects.filter(published=True)
    
    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        context.update({'categories': Category.objects.all()})
        return context

class BookDetailView(DeleteView):
    model = Book
    template_name = 'book/detail.html'
    slug_url_kwarg = 'slug'

def cart_add(request, slug):
    book = get_object_or_404(Book, slug=slug)
    cart_items = request.session.get('cart_items') or []

    duplicate = False 

    for  c in cart_items:
        if c.get('name') == book.name:
            c['qty'] = int(c.get('qty') or '1') +1
            duplicate = True # พบสินค้าชิ้นนี้ในตะกร้า
    # ถ้าไม่มีสินค้านี้ในตะกร้า
    if not duplicate:
        cart_items.append({
            'id': book.id ,
            'name': book.name,
            'slug': book.slug,
            'price': book.price,
            'qty': 1
        })
    total_qty = sum(item.get('qty', 0) for item in cart_items)
    request.session['cart_items'] = cart_items
    request.session['cart_qty'] = total_qty
    return HttpResponseRedirect(reverse('book:cart_list'))

def cart_list(request):
    cart_items = request.session.get('cart_items') or []
    total_qty = 0
    for c in cart_items:
        total_qty += c.get('qty')
    request.session['cart_qty'] = total_qty
    return render(request, 'book/cart.html',{
        'cart_items': cart_items,
    })

def cart_delete(request, slug):
    cart_items = request.session.get('cart_items') or []
    for i in range(len(cart_items)):
        if cart_items[i]['slug'] == slug:
            del cart_items[i]
            break
    total_qty = sum(item.get('qty', 0) for item in cart_items)
    request.session['cart_items'] = cart_items
    request.session['cart_qty'] = total_qty
    return HttpResponseRedirect(reverse('book:cart_list'))

def cart_checkout(request):
    subject = 'Test Email'
    body = ''' 
    <p>This is a test email message ja.</p>
    '''
    email = EmailMessage(
        subject=subject,
        body=body,
        from_email='kk4.yinyin4@gmail.com',
        to=['kanokwan.kum4@gmail.com']
    )
    email.content_subtype = 'html'  # เพื่อส่งเป็น HTML
    email.send()

    return HttpResponseRedirect(reverse('book:index'))

templates/book/add.html
{% extends "layouts/base.html" %}
{% load humanize %}
{% load crispy_forms_tags %}
{% block title %}Book Add{% endblock %}
{% block content %}
<h1>Add a New Book</h1>
<div class="row mb-5">
    <div class="col-lg-6 offset-lg-3">
        <form method="post" enctype="multipart/form-data" novalidate >
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Add Book</button>
        </form>
    </div>
</div>

{% endblock %}

templates/book/cart.html
{% extends "layouts/base.html" %}
{% load humanize %}
{% load crispy_forms_tags %}
{% block title %}Shopping Cart{% endblock %}
{% block content %}
<div class="row">
    <div class="col-lg-6 offset-lg-3">
        <h1>Cart List</h1>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Book Title</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart_items %}
                <tr>
                    <td>{{ item.name }}</td>
                    <td>{{ item.qty }}</td>
                    <td>{{ item.price|floatformat:2|intcomma }}</td>
                    <td>
                        <a href="{% url 'book:cart_delete' slug=item.slug %}" class="btn btn-danger">Remove</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'book:cart_checkout' %}" class="btn btn-primary btn-lg float-right">Checkout</a>
    </div>
</div>

{% endblock %}

templates/book/detail.html
{% extends "layouts/base.html" %}
{% load humanize %}
{% block title %}Book detail{% endblock %}
{% block content %}
<div class="row">
    <div class="col-lg-2">
        {% if book.image %}
        <img src="{{ book.image.url }}" alt="{{ book.title }}" class="img-fluid mb-4">
        {% endif %}
    </div>
    <div class="col-lg-10">
        <h1>{{ book.name }}</h1>
        <div>Category: {{ book.category.name }}</div>
        <div>Price: {{ book.price|floatformat:2|intcomma }}</div>
        <a href="{% url 'book:cart_add' slug=book.slug %}" class="btn btn-success mt-4">Add to Cart</a>
    </div>
</div>
<a href="{% url 'book:index' %}">Back to Book List</a>

<h1>Comment ({{ book.get_comment_count }})</h1>
{% for c in book.bookcomment_set.all %}
<div class="card mb-4">
    <h5>{{c.comment}}</h5>
    <div>Rating: {{c.rating}}</div>
</div>

{% endfor %}

{% endblock %}

templates/book/index.html
{% extends "layouts/base.html" %}
{% load humanize %}
{% block title %}Book Page{% endblock %}
{% block content %}
<h1>Book List</h1>
<a href="{% url 'book:book_add' %}" class="btn btn-warning mb-4">Add New Book</a>
<hr>
<div class="row">
    <!-- Sidebar -->
    <div class="col-lg-2">
        <div class="list-group">
            <a href="{% url 'book:index' %}" 
               class="list-group-item list-group-item-action {% if not categ_id %}active{% endif %}" 
               aria-current="true">
                All
            </a>
            {% for c in categories %}
            <a href="{% url 'book:index' %}?categoryid={{ c.id }}" 
               class="list-group-item list-group-item-action {% if categ_id|add:'0' == c.id %}active{% endif %}">
                {{ c.name }}
            </a>
            {% endfor %}
        </div>
    </div>

    <!-- Main content -->
    <div class="col-lg-10">
        <div class="row">
            {% for book in books %} 
            <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                <div class="card h-100 mb-4">
                    <a href="{% url 'book:detail' slug=book.slug %}">
                        {% if book.image %}
                            <img src="{{ book.image.url }}" alt="{{ book.title }}" class="card-img-top">
                        {% endif %}
                    </a>
                    <div class="card-body">
                        <h5><a href="{% url 'book:detail' slug=book.slug %}">{{ book.name }}</a></h5>
                        <div>Category: {{ book.category.name }}</div>
                        <div>Price: {{ book.price|floatformat:2|intcomma }}</div> <!-- Format price with commas -->
                        <div>Author:</div>
                        {% for a in book.authors.all %}
                        <span class="badge bg-secondary">{{ a.name }}</span>
                        {% endfor %}
                        <br>
                        <a href="{% url 'book:detail' slug=book.slug %}" class="btn btn-info mt-4">View Details</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
            <li class="page-item {% if page_obj.number == i %} active {% endif %}"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            {% endif %}
        </ul>
    </div>
</div>
{% endblock %}