book/urls.py
from django.urls import path , re_path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # path('',views.index , name='index'),
    path('',login_required(views.BookListView.as_view(),login_url='/login'), name='index'),
    # path('detail/<slug:slug>/', views.detail, name='detail'),
    path('detail/<slug:slug>/', views.BookDetailView.as_view(), name='detail'),
    re_path(r'add/$', views.book_add, name='book_add'),

    re_path(r'cart/add/(?P<slug>[\w-]+)/$', views.cart_add, name='cart_add'),
    re_path(r'cart/delete/(?P<slug>[\w-]+)/$', views.cart_delete, name='cart_delete'),
    re_path(r'cart/list/$', views.cart_list, name='cart_list'),
    re_path(r'cart/checkout/$', views.cart_checkout, name='cart_checkout'),
]

myapp/urls.py
from django.urls import path , re_path
from . import views

urlpatterns = [
    path('',views.index , name='index'),
    path('login/',views.login_view , name='login'),
    path('logout/',views.logout_view , name='logout'),
    path('signup/',views.signup_view , name='signup'),
    path('hello/<int:id>',views.hello , name='hello'),
    re_path(r'article/(?P<year>[0-9]{4})/(?P<slug>[\w-]+)$', views.article , name='article'),
]

testproject/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf .urls.static import static
from book.api import router as book_router
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('myapp.urls', 'myapp'), namespace='myapp')),
    path('book/', include(('book.urls', 'book'), namespace='book')),
    path('api/', include(book_router.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/index.html
{% extends "layouts/base.html" %}
{% block title %}Index Page{% endblock %}
{% block content %}
    <h1>Hello, index page!</h1>
    <p>ID: {{id}}</p>
    <p>Name: {{name}}</p>
    <p>Email: {{email}}</p>
    <ul>
        {% for a in activities %}
        <li>{{a}}</li>
        {% endfor %}
    </ul>
    {% if id == '001' and name == 'aomnaiiii' %}
        <h2>เข้าสู่ระบบสำเร็จ</h2>
    {% else %}
        <h2>เข้าสู่ระบบล้มเหลว</h2>
    {% endif %}

    <a href="{% url 'myapp:index' %}">Go to Index</a><br>
    <a href="{% url 'myapp:hello' id=123 %}">Go to Hello</a><br>
    <a href="{% url 'myapp:article' year=2024 slug='my-first-article' %}">Go to Article</a><br>
    <a href="{% url 'book:index' %}">Go to Book page</a>
{% endblock %}